// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5fjD7YXlTlFaQrbrB9DolxA6iieYqhIE',
    appId: '1:874828933771:web:75df7f5a062e3f4c46828e',
    messagingSenderId: '874828933771',
    projectId: 'psoriasis-app',
    authDomain: 'psoriasis-app.firebaseapp.com',
    storageBucket: 'psoriasis-app.appspot.com',
    measurementId: 'G-ES0YKHWM98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrM1s4z7yRqGKlEEnqfdfSwzVzROSTigM',
    appId: '1:874828933771:android:835654f6e1a2238f46828e',
    messagingSenderId: '874828933771',
    projectId: 'psoriasis-app',
    storageBucket: 'psoriasis-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6zsB56uHFgrw-6xO-FJzma9YtGlPbWw4',
    appId: '1:874828933771:ios:ec1ad1208c0ee11f46828e',
    messagingSenderId: '874828933771',
    projectId: 'psoriasis-app',
    storageBucket: 'psoriasis-app.appspot.com',
    iosClientId: '874828933771-6qhbrfmhum7c730qm1396o3bqi446cjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
